apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: rails-config
data:
  RAILS_ENV: 'development'
  # MYSQL_HOST: 'mysql'
  # MYSQL_USER: 'root'
  # MYSQL_ROOT_PASSWORD: 'password'
  TWITTER_API_KEY: 'REPLACE_ME'
  TWITTER_API_SECRET: 'REPLACE_ME'
