apiVersion: batch/v1
kind: Job
metadata:
  namespace: default
  name: setup
spec:
  template:
    metadata:
      name: setup
    spec:
      containers:
        - name: setup
          image: kter/blockshare:latest
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args: ["-c", "bundle exec rake db:create && bundle exec rake db:migrate"]
          envFrom:
            - configMapRef:
                name: rails-config
          env:
            - name: TWITTER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: TWITTER_API_KEY
            - name: TWITTER_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: TWITTER_API_SECRET
      restartPolicy: Never