apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: rails
spec:
  selector:
    app: rails
  type: ClusterIP
  ports:
    - name: "rails-port"
      protocol: "TCP"
      port: 3000
      targetPort: 3000
  #type: NodePort
  #ports:
  #  - port: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: rails
spec:
  selector:
    matchLabels:
      app: rails
  template:
    metadata:
      labels:
        app: rails
    spec:
      containers:
        - name: rails
          image: kter/blockshare:latest
          imagePullPolicy: Always
          command: ["bundle", "exec", "rails", "s", "-b", "0.0.0.0"]
          envFrom:
            - configMapRef:
                name: rails-config
          env:
            - name: TWITTER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: TWITTER_API_KEY
            - name: TWITTER_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: TWITTER_API_SECRET
          ports:
            - containerPort: 3000